# Generated by Django 4.0.4 on 2023-04-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_antigo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('idade', models.IntegerField(verbose_name='idade')),
                ('salario', models.FloatField(verbose_name=models.IntegerField(verbose_name='idade'))),
            ],
            options={
                'db_table': 'registro_funcionarios',
            },
        ),
    ]
