# Generated by Django 4.0.4 on 2023-04-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_antigo', '0002_registro_funcionario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro_funcionario',
            new_name='registro_funcionarios',
        ),
    ]
