# Generated by Django 4.1 on 2022-12-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0004_alter_funcionario_departamento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionario",
            old_name="Empresa",
            new_name="empresa",
        ),
    ]
