# Generated by Django 4.1 on 2022-12-24 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departamentos", "0001_initial"),
        ("funcionarios", "0006_alter_funcionario_departamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="departamento",
            field=models.ManyToManyField(
                related_name="funcionarios", to="departamentos.departamento"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
