# Generated by Django 4.1 on 2022-12-24 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departamentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("funcionarios", "0007_alter_funcionario_departamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="departamento",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="funcionarios",
                to="departamentos.departamento",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funcionario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
