# Generated by Django 4.1 on 2022-12-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamentos", "0002_departamento_empresa"),
        ("funcionarios", "0008_alter_funcionario_departamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="departamento",
            field=models.ManyToManyField(
                related_name="funcionarios", to="departamentos.departamento"
            ),
        ),
    ]
