# Generated by Django 4.1 on 2022-12-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
        ("departamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="Empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departamentos",
                to="empresa.empresa",
            ),
            preserve_default=False,
        ),
    ]
