# Generated by Django 4.1 on 2023-01-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departamentos", "0002_departamento_empresa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="departamento",
            old_name="Empresa",
            new_name="empresa",
        ),
    ]
