# Generated by Django 4.1 on 2023-04-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0009_alter_funcionario_departamento"),
        ("hora_extra", "0004_hora_extra_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="hora_extra",
            name="horas_utilizadas",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="hora_extra",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="horas_extras",
                to="funcionarios.funcionario",
            ),
        ),
    ]
