# Generated by Django 4.1 on 2023-01-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_alter_documento_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(default=1, upload_to="media/documents"),
            preserve_default=False,
        ),
    ]
