# Generated by Django 4.1 on 2023-01-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0009_alter_funcionario_departamento"),
        ("documentos", "0004_documento_arquivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos",
                to="funcionarios.funcionario",
            ),
        ),
    ]
