# Generated by Django 4.1 on 2023-04-10 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresa", "0002_empresa_dono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empresa",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
